services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker
    volumes:
      - ./scrapy_app/output:/tmp
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis

  beat:
    build: .
    container_name: celery_beat
    volumes:
      - ./scrapy_app/output:/tmp
    command: celery -A celerybeat_schedule beat --loglevel=info
    depends_on:
      - redis

  flower:
    build: .
    container_name: celery_flower
    command: celery -A tasks flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
